# -- Pod name
name: mongodb
# -- Number of replica nodes
replicaCount: 3
extraLabels: {}
# -- Mongodb image information
image:
  repository: mongo
  tag: "8.0"
  pullPolicy: IfNotPresent
# -- Credentials for the deployment
auth:
  adminUser: "admin-user"
  adminPassword: "admin-password"
  database: "db1"
  dbUser: "dbuser"
  dbPassword: "dbpass"
# -- Name of the replicaSet to create from the replica nodes
replicaSet: rs0
persistence:
  storageClass: ""
  size: 8Gi
# -- Resources available for the containers
resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"
# -- Security context for the deployment
securityContext:
  privileged: true
  allowPrivilegeEscalation: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - all
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    partition: 0
service:
  type: ClusterIP
  port: "27017"
  externalAccess:
      enabled: false
      type: LoadBalancer
pdb:
  enabled: true
  maxUnavailable: 1
backup:
  enabled: true
  cronjob:
    schedule: "0 0 * * *"
  storage:
    type: emptyDir
    pvc:
      enabled: false
      storageClass: ""
      size: 10Gi
    s3:
      enabled: false
      bucket: ""
      credentialsSecret: ""
  credentials:
    username: dbuser
    password: dbpass
    existingSecret: ""