{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-init-secret" .Values.name)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-init-secret
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.auth.adminUser | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.auth.adminPassword | b64enc | quote }}
  KEYFILE: {{ if $existingSecret }}{{ $existingSecret.data.KEYFILE | default (randAlphaNum 256 | b64enc) | quote }}{{ else }}{{ randAlphaNum 512 | b64enc | quote }}{{ end }}
